[versions]
kotlin = "1.9.0"
kotlinx-datetime = "0.4.0"
exposed = "0.42.0"
postgres = "42.6.0"
logback = "1.4.8"

[libraries]
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-money = { module = "org.jetbrains.exposed:exposed-money", version.ref = "exposed" }
exposed-json = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[bundles]
exposed = ["exposed-core", "exposed-jdbc", "exposed-money", "exposed-json", "exposed-kotlin-datetime"]
